[package]
name = "dcs-bios-cli"
version = "0.1.0"
edition = "2021"
description = "Simple command line interface for DCS BIOS"

[dependencies]
dcs-bios = { workspace = true }
clap = { version = "4.5.20", features = ["derive"] }

clap-num = "1.1.1"